### ISSUE TITLE
Suggestions on the package

### ISSUE THREAD

**Issue by wenlong-liu** [ropensci/rnassqs#16]
Finally I have sometime to work with this package.  It is very powerful and easy to use.  Most importantly, it can be fully reproducible.  

Some suggestions:
1. It is helpful to force the params converted to upper case.  Sometimes I accidentally write the params in lower case and it is very difficult to find the error caused by typo.

2. If possible, is there a way to wrap a function to generate the params.  It will be very straightforward for users to fetch batch dataset.

I am willing to contribute some codes related to these topic if needed.  Thank you for providing this useful package.

Best,
Wenlong

**Comment by econpotter** [comment]
@wenlong-liu Thanks! 

There will be a new version 0.5.0 on CRAN soon that handles parameter case so that you don't have to work about it. In the meantime you can reinstall with `devtools::install_github("ropensci/rnassqs")`. 

How do you imagine the second suggestion working? Do you mean something that would make it easier to fetch specific data like the `nassqs_yields()` and `nassqs_acres()` functions? Or something else? It would be great to expand those and add a bunch of helper functions that would allow easier downloading of specific data.

Any pull requests you would like to make would be welcome. Please look at the [CONTRIBUTING](https://github.com/ropensci/rnassqs/blob/master/CONTRIBUTING.md) file. You can make a pull request based on this issue, but it might be helpful to discuss more what you're thinking for addressing your second suggestion.

**Comment by wenlong-liu** [comment]
@potterzot Thank you for the reminding of the parameter case.  I figured it out according to the latest version of the package.  

For the second topic, the helper functions regarding yields and area are very helpful. Actually I just used this package to pull some area data in US.  It works like a charm.

What I was thinking is a wrapper to feed the parameters in the _nassqs_GET()_.  For example, the current workflow to pass parameters is:

    params <- list(commodity_name = "CORN",
                 year = 2012,
                 agg_level_desc = "STATE",
                 state_alpha = "WA",
                 statisticcat_desc = "YIELD")

     # Returns a request object that must be parsed either manually or by using nassqs_parse()

     response <- nassqs_GET(params)
     yields <- nassqs_parse(response)
     head(yields)

Is it possible to add a wrapper function in the backend, so the users can directly use the function as (or similar form):

      # Returns a request object that must be parsed either manually or by using nassqs_parse()

     response <- nassqs_GET(
                 commodity_name = "CORN",
                 year = 2012,
                 agg_level_desc = "STATE",
                 state_alpha = "WA",
                 statisticcat_desc = "YIELD")

     yields <- nassqs_parse(response)
     head(yields)   

Hope it helps.

Best,
Wenlong

**Comment by econpotter** [comment]
```{r}
# Returns a request object that must be parsed either manually or by using nassqs_parse()

 response <- nassqs_GET(
             commodity_name = "CORN",
             year = 2012,
             agg_level_desc = "STATE",
             state_alpha = "WA",
             statisticcat_desc = "YIELD")

 yields <- nassqs_parse(response)
 head(yields)   
```

This is possible in the current master branch, with no need to access `nassqs_GET()` directly. You can for instance just do:

```{r}
 response <- nassqs(
             commodity_name = "CORN",
             year = 2012,
             agg_level_desc = "STATE",
             state_alpha = "WA",
             statisticcat_desc = "YIELD")
```

with no need for putting the parameters in a list if you prefer not to. This will still return a `data.frame` instead of a `httr::GET()` object, but I think that's what you'd like in this case right? Or do you want access to the unparsed object? In which case you can use `nassqs_GET()` as you specify in your example, with each parameter as a named input to the function.
