### ISSUE TITLE
"Value" field is character instead of numeric

### ISSUE THREAD

**Issue by econpotter** [ropensci/rnassqs#2]
Do we want to make this numeric by default? Risks converting all symbolic missing entries like "(Z)", "(D)", etc... into generic NAs. One option: provide "as.numeric" as a function parameter so the user can decide.

**Comment by PieceMaker** [comment]
I would ask that this not be the default since we are not guaranteed that `Value` will always be a number. Additionally, I do not see much value passing a transform function into the request since it would be just as easy to run

```R
data$Value <- as.numeric(gsub(",", "", data$Value))
```

after the fact and you're almost guaranteed to need to do other transformations after the data has been returned anyway.

**Comment by econpotter** [comment]
@PieceMaker thanks for the feedback, I feel the same way, would prefer to let the user do any post-processing, returning the data in an unchanged form. Glad to have your thoughts. There was another user who had requested returning values as numeric, hence the potential for a parameter to do so.

**Comment by econpotter** [comment]
Closing since there seems to be agreement about leaving the values as unprocessed strings instead of doing any processing before returning to the user.
