### ISSUE TITLE
Make a county fips code option?

### ISSUE THREAD

**Issue by econpotter** [ropensci/rnassqs#30]
From @rdinter :

County FIPS is an obvious argument to be implemented in this package! It's frustrating that county_code is not was most people would regard as a FIPS code. A simple concatenation of state_fips_code and county_code creates a FIPS so it should be straightforward to reverse this in making API calls (ie county_fips as an argument that gets passed along to state_fips_code and county_code in an API call)

**Comment by rdinter** [comment]
This is great to bring up again, although I am trying to recall whether or not I meant for a FIPS code to be an output or an input option. It is definitely straightforward to have FIPS as an output since it would be a concatenation of state_fips_code and county_code. To make FIPS an an input for a quickstats query it is trickier to do, but I think it could still be implemented somehow.

If I want to query for corn yield in Adair County Iowa (19001) then breaking apart the FIPS works:
```
nassqs(commodity_desc = "CORN",
       state_fips_code = "19",
       county_code = "001",
       year = 2019,
       statisticcat_desc = "YIELD")

```
Including Allamakee County (19005) would be adding on another county FIPS code to the previous query:
```
nassqs(commodity_desc = "CORN",
       state_fips_code = "19",
       county_code = c("001", "005"),
       year = 2019,
       statisticcat_desc = "YIELD")
```
I would say those two above work as expected and if I passed an argument of `FIPS = c("19001", "19005")` one could extract the necessary state and county FIPS codes with one fewer argument in the query. But if we want to cross state lines and include say Adams County Illinois (17001) then adding that to the query will "unnecessarily" include Bond County Illinois (17005):
```
nassqs(commodity_desc = "CORN",
       state_fips_code = c("19", "17"),
       county_code = c("001", "005"),
       year = 2019,
       statisticcat_desc = "YIELD")

```

It seems to me there are two paths in achieving the "correct" number of FIPS in a query. One would be to do some post-processing of the results of a query to remove unnecessary observations like Bond County in the above example. The other, and probably preferred solution, is to pass multiple queries if there is more than 1 state involved with a list of FIPS codes.

**Comment by econpotter** [comment]
Trying to clean up some of these, this is a nice idea. Working off your example, maybe a wrapper would be useful, something like:

```
nassqs_byfips <- function(fips, ...) {
  states <- unique(substr(fips, 1, 2))
  lapply(states, function(st) {
    Sys.sleep(1)
    nassqs(
      state_fips_code = st,
      county_code = substr(grep(st, fips, value = TRUE), 3, 5),
      ...)
    }) |> dplyr::bind_rows()
}

nassqs_byfips(
  fips = c("19001", "17005", "17001"),
  commodity_desc = "CORN",
  year = 2019,
  statisticcat_desc = "YIELD")
```

**Comment by econpotter** [comment]
Added this as `nassqs_byfips()`
