### ISSUE TITLE
Add county FIPS codes

### ISSUE THREAD

**Issue by econpotter** [ropensci/rnassqs#4]
Would make it easier for some users if the dataset returned at the county level included county-level FIPS codes.

**Comment by PieceMaker** [comment]
These are already returned, but are referred to as [ANSI](https://www.census.gov/geo/reference/ansi.html) instead of FIPS. For the state code, there is `data.state_ansi` which is effectively the FIPS code and there is `data.state_fips_code` which, despite the name, is actually a custom NASS code which is based on FIPS but also includes codes 99 (total US) and 98 (other states). Other states in this context means any remainders they were not allowed to report with a state association due to PII laws.

For the county code, `data.county_ansi` should serve as the county-level FIPS you are wanting. There is also `data.county_code` which is another NASS adaptation that contains some other catch-all codes.

See the [API docs](https://quickstats.nass.usda.gov/api) for NASS' descriptions of these fields.

**Comment by econpotter** [comment]
Excellent, I thought that the fips codes were there but couldn't remember. Thanks!
